from directx import *
# SNES KEYS
# Note: arrow keys do not work for some reason on SNES emulator, use other keys
SNES_P1_UP = V
SNES_P1_DOWN = B
SNES_P1_LEFT = N
SNES_P1_RIGHT = M
SNES_P1_A = X
SNES_P1_B = Z
SNES_P1_L = Q
SNES_P1_R = E
SNES_P1_X = C
SNES_P1_Y = R
SNES_P1_START = ENTER
SNES_P1_SELECT = RIGHT_SHIFT

SNES_P2_UP = I
SNES_P2_DOWN = K
SNES_P2_LEFT = J
SNES_P2_RIGHT = L
SNES_P2_A = G
SNES_P2_B = F
SNES_P2_L = O
SNES_P2_R = P
SNES_P2_X = T
SNES_P2_Y = H
SNES_P2_START = SEMICOLON
